export const BUTTON_ADD_PRODUCT = 'Add Product'
export const BUTTON_EDIT_PRODUCT = 'Edit'
export const BUTTON_DELETE_PRODUCT = 'Delete'
export const BUTTON_CANCEL = 'Cancel'
export const BUTTON_SAVE = 'Save'
